# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

env:
  PATH: $PATH:$HOME/.shadow/bin

jobs:
  testing:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        cc: ['gcc', 'clang']
#${{ matrix.cc }} \
    
    steps:
      - name: Install shadow build deps
        run: >
          sudo apt-get install -y
          gcc
          g++
          cmake
          make
          xz-utils
          python
          libglib2.0-0
          libglib2.0-dev
          libigraph0v5
          libigraph0-dev
          libc-dbg
          python-pyelftools

      - name: Checkout Shadow
        uses: actions/checkout@v2
        with:
          repository: shadow/shadow
          ref: v1.13.2
          path: shadow

      - name: Install Shadow
        working-directory: ./shadow
        run: |
          ./setup build
          ./setup install

      - name: Install shadow-plugin-tor build deps
        run: >
          sudo apt-get install -y
          autoconf
          automake
          gcc
          liblzma5
          liblzma-dev
          zlib1g-dev

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: shadow-plugin-tor

      - name: Build
        working-directory: ./shadow-plugin-tor
        run: |
          ./setup dependencies -y
          ./setup build -y
          ./setup install

      - name: Simulate
        working-directory: ./shadow-plugin-tor/resource
        run: |
          echo ${PATH}  # temp
          tar xaf shadowtor-minimal-config.tar.xz
          mv shadowtor-minimal-config shadowtor-minimal
          cd shadowtor-minimal
          shadow shadow.config.xml > shadow.log
          COMPLETE=`find shadow.data/hosts -name '*client*.log' -exec grep transfer-complete \{\} \; | wc -l`
          if [ $COMPLETE -ne 40 ]; then echo Expected 40 transfers got $COMPLETE; exit 1; fi

