# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  testing:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        cc: ['gcc', 'clang']
#${{ matrix.cc }} \
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Apt update
        run: sudo apt-get update

      - name: Apt install
        run: >
            sudo apt-get install -y
            gcc
            autoconf
            automake
            cmake
            g++
            libc-dbg
            libglib2.0-0
            libglib2.0-dev
            libigraph0-dev
            libigraph0v5
            liblzma5
            liblzma-dev
            make
            python
            python-pyelftools
            xz-utils
            zlib1g-dev

      - name: Dependencies
        run: ./setup dependencies

      - name: Build
        run: ./setup build

      - name: Install
        run: ./setup install
